### ISSUE TITLE
Crop small pages

### ISSUE THREAD

**Issue by fonsp** [fonsp/printi-channels#1]
Firefox headless rendering seems to have a _minimum page height_, which causes short pages to have a bunch of trailing white space. (Which becomes glitchy in error-diffusion dithering)

![89](https://user-images.githubusercontent.com/6933510/72977504-fde18d80-3dd4-11ea-8211-31c75d49de6e.png)

**Comment by malyvsen** [comment]
This could also serve as a simple "nothing to print" mechanism - eg. if a channel wants to be weekly rather than daily
